var gihubResponses = {
  'comments': [
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/60814434",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-60814434",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 60814434,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-28T19:15:26Z",
    "updated_at": "2014-10-28T19:15:26Z",
    "body": "@michaelcarter-wf @bradybecker-wf @mikekeil-wf \r\n\r\nA temporary fix but easily updated when the icon becomes available.  The related pull request is for a minor style tweak necessary to apply the proper color, as requested by @hannahdeering-wf "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/60814552",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-60814552",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 60814552,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-28T19:16:09Z",
    "updated_at": "2014-10-28T19:16:09Z",
    "body": "@hannahdeering-wf  Per your instructions.  The color difference is quite subtle:\r\n\r\n![icon_compare](https://cloud.githubusercontent.com/assets/2872166/4815424/d0af5956-5ed6-11e4-820b-0814f1bda592.png)\r\n"
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/60814716",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-60814716",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 60814716,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-28T19:17:14Z",
    "updated_at": "2014-10-28T19:17:14Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/60839237",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-60839237",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 60839237,
    "user": {
      "login": "hannahdeering-wf",
      "id": 5629760,
      "avatar_url": "https://avatars.githubusercontent.com/u/5629760?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hannahdeering-wf",
      "html_url": "https://github.com/hannahdeering-wf",
      "followers_url": "https://api.github.com/users/hannahdeering-wf/followers",
      "following_url": "https://api.github.com/users/hannahdeering-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/hannahdeering-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hannahdeering-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hannahdeering-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/hannahdeering-wf/orgs",
      "repos_url": "https://api.github.com/users/hannahdeering-wf/repos",
      "events_url": "https://api.github.com/users/hannahdeering-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hannahdeering-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-28T21:58:54Z",
    "updated_at": "2014-10-28T21:58:54Z",
    "body": "I don't think the color is actually getting applied. It should be the same color as DC. It looks like icon-color places an !important flag, so is actually overriding with the workbook color."
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/60842808",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-60842808",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 60842808,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-28T22:26:12Z",
    "updated_at": "2014-10-28T22:26:12Z",
    "body": "@hannahdeering-wf Whoops!  Ok, I'll fix asap."
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61129844",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61129844",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61129844,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-30T17:10:16Z",
    "updated_at": "2014-10-30T17:10:16Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61261571",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61261571",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61261571,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-31T13:45:21Z",
    "updated_at": "2014-10-31T13:45:21Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61267586",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61267586",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61267586,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-31T14:26:51Z",
    "updated_at": "2014-10-31T14:26:51Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61302290",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61302290",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61302290,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-31T18:03:16Z",
    "updated_at": "2014-10-31T18:03:16Z",
    "body": "@michaelcarter-wf @mikekeil-wf @bradybecker-wf\r\n\r\nFinally! A passing build. Please :+1: before something else happens :smile:"
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61307345",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61307345",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61307345,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-31T18:31:32Z",
    "updated_at": "2014-10-31T18:31:32Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61320689",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61320689",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61320689,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-10-31T19:53:19Z",
    "updated_at": "2014-10-31T19:53:19Z",
    "body": ":+1: :money_with_wings: "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61499531",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61499531",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61499531,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-11-03T15:59:29Z",
    "updated_at": "2014-11-03T15:59:29Z",
    "body": "@michaelcarter-wf @mikekeil-wf @bradybecker-wf\r\n\r\nAnother quick look after the upstream merge, please?  Thanks!"
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61501580",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61501580",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61501580,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-11-03T16:11:43Z",
    "updated_at": "2014-11-03T16:11:43Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61506747",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61506747",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61506747,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-11-03T16:42:01Z",
    "updated_at": "2014-11-03T16:42:01Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/comments/61516525",
    "html_url": "https://github.com/jimhotchkin-wf/web-bones/pull/20#issuecomment-61516525",
    "issue_url": "https://api.github.com/repos/jimhotchkin-wf/web-bones/issues/20",
    "id": 61516525,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=2",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-11-03T17:41:11Z",
    "updated_at": "2014-11-03T17:41:11Z",
    "body": "+1"
  }
]
};

module.exports = gihubResponses; 

