name: 'wChaser'
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser_detect: ">=1.0.0 <2.0.0"
  react: ">=0.6.0"
  web_skin_dart:
    git:
      url: git@github.com:Workiva/web_skin_dart.git
      ref: 0.0.5
dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.0"
  dartdoc: "^0.4.0"
  source_gen: "^0.4.1"
  test: "^0.12.0"
  w_flux:
    git:
      url: git@github.com:Workiva/w_flux.git
      ref: 0.3.0
dependency_overrides:
  dart_style: "^0.2.0"