name: 'wChaser'
version: 2.0.0
description: Chrome extension that chases pull requests that you've open or have been mentioned in
author: Brady Becker bradybeck@gmail.com
environment:
  sdk: ">=1.9.0 <2.0.0"
dependencies:
  browser_detect: ">=1.0.0 <2.0.0"
  chrome: any
  dart_to_js_script_rewriter: 1.0.1
  dart_coveralls: 0.4.0
  fluri: 1.1.1
  grinder: "^0.8.0+1"
  intl: 0.12.4+2
  lawndart: any
  react: "^1.0.0"
  sass: any
  unittest: any
  w_flux: "^2.0.0"

dev_dependencies:
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "0.2.0"
  dartdoc: "^0.4.0"
  source_gen: "^0.4.1"
  test: "^0.12.0"

transformers:
  - dart_to_js_script_rewriter
  # - chrome
  - sass
