name: 'wChaser'
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  pubsub: ">=1.1.9 <2.0.0"
  react: ">=0.5.0 <0.6.0"
  web_skin_react:
    git:
      url: git@github.com:Workiva/web-skin-react.git
      ref: 1.1.0
