final List commentResponse = [
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/148051515",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-148051515",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 148051515,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-14T13:37:57Z",
    "updated_at": "2015-10-14T13:38:02Z",
    "body": ":+1:   Re: testing: wouldn't a mock w_session object do the trick?"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151297399",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151297399",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151297399,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-26T22:03:57Z",
    "updated_at": "2015-10-26T22:03:57Z",
    "body": "ready for another round: FYA: @jimhotchkin-wf @bradybecker-wf @mikekeil-wf @kennethmai-wf"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151521325",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151521325",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151521325,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T14:38:29Z",
    "updated_at": "2015-10-27T14:38:29Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151522391",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151522391",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151522391,
    "user": {
      "login": "kennethmai-wf",
      "id": 1480517,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480517?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethmai-wf",
      "html_url": "https://github.com/kennethmai-wf",
      "followers_url": "https://api.github.com/users/kennethmai-wf/followers",
      "following_url": "https://api.github.com/users/kennethmai-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethmai-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethmai-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethmai-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethmai-wf/orgs",
      "repos_url": "https://api.github.com/users/kennethmai-wf/repos",
      "events_url": "https://api.github.com/users/kennethmai-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethmai-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T14:40:24Z",
    "updated_at": "2015-10-27T14:40:24Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151531747",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151531747",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151531747,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T15:03:31Z",
    "updated_at": "2015-10-27T15:03:31Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151534559",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151534559",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151534559,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T15:10:14Z",
    "updated_at": "2015-10-27T15:10:14Z",
    "body": "Code Review Complete"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151562408",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151562408",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151562408,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T16:38:25Z",
    "updated_at": "2015-10-27T16:38:25Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151961661",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151961661",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151961661,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-28T19:16:23Z",
    "updated_at": "2015-10-28T19:16:23Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151963886",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151963886",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151963886,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-28T19:26:07Z",
    "updated_at": "2015-10-28T19:26:07Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151964124",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151964124",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151964124,
    "user": {
      "login": "kennethmai-wf",
      "id": 1480517,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480517?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethmai-wf",
      "html_url": "https://github.com/kennethmai-wf",
      "followers_url": "https://api.github.com/users/kennethmai-wf/followers",
      "following_url": "https://api.github.com/users/kennethmai-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethmai-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethmai-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethmai-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethmai-wf/orgs",
      "repos_url": "https://api.github.com/users/kennethmai-wf/repos",
      "events_url": "https://api.github.com/users/kennethmai-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethmai-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-28T19:27:03Z",
    "updated_at": "2015-10-28T19:27:03Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154488604",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154488604",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154488604,
    "user": {
      "login": "kennethmai-wf",
      "id": 1480517,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480517?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethmai-wf",
      "html_url": "https://github.com/kennethmai-wf",
      "followers_url": "https://api.github.com/users/kennethmai-wf/followers",
      "following_url": "https://api.github.com/users/kennethmai-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethmai-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethmai-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethmai-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethmai-wf/orgs",
      "repos_url": "https://api.github.com/users/kennethmai-wf/repos",
      "events_url": "https://api.github.com/users/kennethmai-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethmai-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T18:08:47Z",
    "updated_at": "2015-11-06T18:08:47Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154489629",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154489629",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154489629,
    "user": {
      "login": "jonnykrysh-wf",
      "id": 12497731,
      "avatar_url": "https://avatars.githubusercontent.com/u/12497731?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jonnykrysh-wf",
      "html_url": "https://github.com/jonnykrysh-wf",
      "followers_url": "https://api.github.com/users/jonnykrysh-wf/followers",
      "following_url": "https://api.github.com/users/jonnykrysh-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jonnykrysh-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jonnykrysh-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jonnykrysh-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jonnykrysh-wf/orgs",
      "repos_url": "https://api.github.com/users/jonnykrysh-wf/repos",
      "events_url": "https://api.github.com/users/jonnykrysh-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jonnykrysh-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T18:13:13Z",
    "updated_at": "2015-11-06T18:13:13Z",
    "body": ":+1: - #nit comment above"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154500467",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154500467",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154500467,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T18:54:41Z",
    "updated_at": "2015-11-06T18:54:41Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154514366",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154514366",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154514366,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T19:49:40Z",
    "updated_at": "2015-11-06T19:49:40Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154550503",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154550503",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154550503,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T21:42:57Z",
    "updated_at": "2015-11-06T21:42:57Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155175487",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155175487",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155175487,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-09T20:03:41Z",
    "updated_at": "2015-11-09T20:03:41Z",
    "body": "@bradybecker-wf :eyes: on the last commit (had to make IE happy re: user events for opening a new tab)."
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155180475",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155180475",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155180475,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-09T20:18:48Z",
    "updated_at": "2015-11-09T20:18:48Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155791124",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155791124",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155791124,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T14:01:39Z",
    "updated_at": "2015-11-11T14:01:39Z",
    "body": "Dev QA +10:\r\n- [x] Tested in IE10\r\n- [x] Tested in IE11\r\n- [x] Tested in Firefox\r\n- [x] APE Button opens APE App\r\n- [x] Content admin always gets permission to edit, even if viewer on doc.\r\n- [x] Non-content admin sees button when is a creator and own's doc\r\n- [x] Non-content admin - ape button disappears if a change is made removing owner permission for self\r\n- [x] Non-content admin - doesn’t see button if not owner of doc."
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155791166",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155791166",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155791166,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T14:01:54Z",
    "updated_at": "2015-11-11T14:03:50Z",
    "body": "@jimhotchkin-wf || @bradybecker-wf || @mikekeil-wf one more +1 on the last commit?"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155792067",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155792067",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155792067,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T14:05:03Z",
    "updated_at": "2015-11-11T14:05:03Z",
    "body": ":+1: :100: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155921813",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155921813",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155921813,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T21:55:16Z",
    "updated_at": "2015-11-11T21:55:22Z",
    "body": "@jimhotchkin-wf || @bradybecker-wf || @mikekeil-wf || @jonnykrysh-wf one more +1 on the last commits?"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155928960",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155928960",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155928960,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T22:25:44Z",
    "updated_at": "2015-11-11T22:25:44Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155932189",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155932189",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155932189,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T22:40:54Z",
    "updated_at": "2015-11-11T22:40:54Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/156123605",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-156123605",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 156123605,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-12T14:47:30Z",
    "updated_at": "2015-11-12T14:47:30Z",
    "body": "Dev QA +10 Round 2 :bell: \r\n\r\n- [x] Tested in IE10\r\n- [x] Tested in IE11\r\n- [x] Tested in Firefox\r\n- [x] APE Button opens APE App\r\n- [x] Content admin always gets permission to edit, even if viewer on doc.\r\n- [x] Non-content admin sees button when is a creator and own's doc\r\n- [x] Non-content admin - ape button disappears if a change is made removing owner permission for self\r\n- [x] Non-content admin - doesn’t see button if not owner of doc."
  }
];
