final List commentResponse = [
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/148051515",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-148051515",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 148051515,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-14T13:37:57Z",
    "updated_at": "2015-10-14T13:38:02Z",
    "body": ":+1:   Re: testing: wouldn't a mock w_session object do the trick?"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151297399",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151297399",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151297399,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-26T22:03:57Z",
    "updated_at": "2015-10-26T22:03:57Z",
    "body": "ready for another round: FYA: @jimhotchkin-wf @bradybecker-wf @mikekeil-wf @kennethmai-wf"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151521325",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151521325",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151521325,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T14:38:29Z",
    "updated_at": "2015-10-27T14:38:29Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151522391",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151522391",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151522391,
    "user": {
      "login": "kennethmai-wf",
      "id": 1480517,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480517?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethmai-wf",
      "html_url": "https://github.com/kennethmai-wf",
      "followers_url": "https://api.github.com/users/kennethmai-wf/followers",
      "following_url": "https://api.github.com/users/kennethmai-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethmai-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethmai-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethmai-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethmai-wf/orgs",
      "repos_url": "https://api.github.com/users/kennethmai-wf/repos",
      "events_url": "https://api.github.com/users/kennethmai-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethmai-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T14:40:24Z",
    "updated_at": "2015-10-27T14:40:24Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151531747",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151531747",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151531747,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T15:03:31Z",
    "updated_at": "2015-10-27T15:03:31Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151534559",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151534559",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151534559,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T15:10:14Z",
    "updated_at": "2015-10-27T15:10:14Z",
    "body": "Code Review Complete"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151562408",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151562408",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151562408,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-27T16:38:25Z",
    "updated_at": "2015-10-27T16:38:25Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151961661",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151961661",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151961661,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-28T19:16:23Z",
    "updated_at": "2015-10-28T19:16:23Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151963886",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151963886",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151963886,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-28T19:26:07Z",
    "updated_at": "2015-10-28T19:26:07Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/151964124",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-151964124",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 151964124,
    "user": {
      "login": "kennethmai-wf",
      "id": 1480517,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480517?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethmai-wf",
      "html_url": "https://github.com/kennethmai-wf",
      "followers_url": "https://api.github.com/users/kennethmai-wf/followers",
      "following_url": "https://api.github.com/users/kennethmai-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethmai-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethmai-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethmai-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethmai-wf/orgs",
      "repos_url": "https://api.github.com/users/kennethmai-wf/repos",
      "events_url": "https://api.github.com/users/kennethmai-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethmai-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-28T19:27:03Z",
    "updated_at": "2015-10-28T19:27:03Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154488604",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154488604",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154488604,
    "user": {
      "login": "kennethmai-wf",
      "id": 1480517,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480517?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kennethmai-wf",
      "html_url": "https://github.com/kennethmai-wf",
      "followers_url": "https://api.github.com/users/kennethmai-wf/followers",
      "following_url": "https://api.github.com/users/kennethmai-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/kennethmai-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kennethmai-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kennethmai-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/kennethmai-wf/orgs",
      "repos_url": "https://api.github.com/users/kennethmai-wf/repos",
      "events_url": "https://api.github.com/users/kennethmai-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kennethmai-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T18:08:47Z",
    "updated_at": "2015-11-06T18:08:47Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154489629",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154489629",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154489629,
    "user": {
      "login": "jonnykrysh-wf",
      "id": 12497731,
      "avatar_url": "https://avatars.githubusercontent.com/u/12497731?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jonnykrysh-wf",
      "html_url": "https://github.com/jonnykrysh-wf",
      "followers_url": "https://api.github.com/users/jonnykrysh-wf/followers",
      "following_url": "https://api.github.com/users/jonnykrysh-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jonnykrysh-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jonnykrysh-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jonnykrysh-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jonnykrysh-wf/orgs",
      "repos_url": "https://api.github.com/users/jonnykrysh-wf/repos",
      "events_url": "https://api.github.com/users/jonnykrysh-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jonnykrysh-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T18:13:13Z",
    "updated_at": "2015-11-06T18:13:13Z",
    "body": ":+1: - #nit comment above"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154500467",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154500467",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154500467,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T18:54:41Z",
    "updated_at": "2015-11-06T18:54:41Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154514366",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154514366",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154514366,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T19:49:40Z",
    "updated_at": "2015-11-06T19:49:40Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/154550503",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-154550503",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 154550503,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-06T21:42:57Z",
    "updated_at": "2015-11-06T21:42:57Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155175487",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155175487",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155175487,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-09T20:03:41Z",
    "updated_at": "2015-11-09T20:03:41Z",
    "body": "@bradybecker-wf :eyes: on the last commit (had to make IE happy re: user events for opening a new tab)."
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155180475",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155180475",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155180475,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-09T20:18:48Z",
    "updated_at": "2015-11-09T20:18:48Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155791124",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155791124",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155791124,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T14:01:39Z",
    "updated_at": "2015-11-11T14:01:39Z",
    "body":
        "Dev QA +10:\r\n- [x] Tested in IE10\r\n- [x] Tested in IE11\r\n- [x] Tested in Firefox\r\n- [x] APE Button opens APE App\r\n- [x] Content admin always gets permission to edit, even if viewer on doc.\r\n- [x] Non-content admin sees button when is a creator and own's doc\r\n- [x] Non-content admin - ape button disappears if a change is made removing owner permission for self\r\n- [x] Non-content admin - doesn’t see button if not owner of doc."
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155791166",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155791166",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155791166,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T14:01:54Z",
    "updated_at": "2015-11-11T14:03:50Z",
    "body": "@jimhotchkin-wf || @bradybecker-wf || @mikekeil-wf one more +1 on the last commit?"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155792067",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155792067",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155792067,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T14:05:03Z",
    "updated_at": "2015-11-11T14:05:03Z",
    "body": ":+1: :100: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155921813",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155921813",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155921813,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T21:55:16Z",
    "updated_at": "2015-11-11T21:55:22Z",
    "body": "@jimhotchkin-wf || @bradybecker-wf || @mikekeil-wf || @jonnykrysh-wf one more +1 on the last commits?"
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155928960",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155928960",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155928960,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T22:25:44Z",
    "updated_at": "2015-11-11T22:25:44Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/155932189",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-155932189",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 155932189,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-11T22:40:54Z",
    "updated_at": "2015-11-11T22:40:54Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/comments/156123605",
    "html_url": "https://github.com/michaelcarter-wf/dart-permissions-editor/pull/7#issuecomment-156123605",
    "issue_url": "https://api.github.com/repos/michaelcarter-wf/dart-permissions-editor/issues/7",
    "id": 156123605,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-12T14:47:30Z",
    "updated_at": "2015-11-12T14:47:30Z",
    "body":
        "Dev QA +10 Round 2 :bell: \r\n\r\n- [x] Tested in IE10\r\n- [x] Tested in IE11\r\n- [x] Tested in Firefox\r\n- [x] APE Button opens APE App\r\n- [x] Content admin always gets permission to edit, even if viewer on doc.\r\n- [x] Non-content admin sees button when is a creator and own's doc\r\n- [x] Non-content admin - ape button disappears if a change is made removing owner permission for self\r\n- [x] Non-content admin - doesn’t see button if not owner of doc."
  }
];

final commentResponseTwo = [
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/205464614",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-205464614",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 205464614,
    "user": {
      "login": "rmconsole-wf",
      "id": 4922439,
      "avatar_url": "https://avatars.githubusercontent.com/u/4922439?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rmconsole-wf",
      "html_url": "https://github.com/rmconsole-wf",
      "followers_url": "https://api.github.com/users/rmconsole-wf/followers",
      "following_url": "https://api.github.com/users/rmconsole-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/rmconsole-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rmconsole-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rmconsole-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/rmconsole-wf/orgs",
      "repos_url": "https://api.github.com/users/rmconsole-wf/repos",
      "events_url": "https://api.github.com/users/rmconsole-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rmconsole-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T19:45:29Z",
    "updated_at": "2016-04-08T19:14:21Z",
    "body":
        "\n## General Information\nTicket(s): [WORK-4131](https://jira.atl.workiva.net/browse/WORK-4131)\nCode Review(s): https://github.com/Workiva/wf-home-html/pull/395\nCI: https://ci.webfilings.com/build/525623\nAutomation: Could not find automation run associated with this pull.\n\n## SOC 1 Checklist\n- [x] All commits reviewed\n- [x] QA Review\n- [x] Security review completed for all commits if applicable: \n   - [x] https://github.com/Workiva/w_oauth2/pull/46#issuecomment-196536601\n\n## Rosie Checklist\n- [x] Smithy build successful\n- [x] Smithy run in past 24 hours\n- [x] Smithy run against most recent commit\n- [x] Unit Tests Updated (Not required for these file types)\n\n**Included Internal Dependencies Unreviewed by RM:**\n*w_flux 2.1.0*\n- [x] [CP-1226 cleanup old tooling, w_flux](https://github.com/Workiva/w_flux/pull/52)\n- [x] [CP-1415 Allow use of react-dart 0.9.0, w_flux](https://github.com/Workiva/w_flux/pull/53)\n- [x] [CP-1193 Release w_flux 2.1.0](https://github.com/Workiva/w_flux/pull/54)\n\n*w_oauth2 1.1.0*\n- [x] [CP-1421 Use Workiva blue for Documentation Badge, w_oauth2](https://github.com/Workiva/w_oauth2/pull/40)\n- [x] [CP-1390 Update smithy runner_image to libc compliant version](https://github.com/Workiva/w_oauth2/pull/43)\n- [x] [CP-1448 Add usePostMessage option and implementation](https://github.com/Workiva/w_oauth2/pull/46)\n- [x] [CP-1379 Release w_oauth2 1.1.0](https://github.com/Workiva/w_oauth2/pull/48)\n\n*w_transport 1.0.0* (previously approved for sandbox use)\n\n*w_transport 1.0.1* (previously approved for sandbox use)\n\n*w_transport 2.0.0* (previously approved for sandbox use)\n\n*w_transport 2.0.1* (previously approved for sandbox use)\n\n*w_transport 2.1.0* (previously approved for sandbox use)\n\n*w_transport 2.2.0* (previously approved for sandbox use)\n\n*w_transport 2.3.0* (previously approved for sandbox use)\n\n*w_transport 2.3.1* (previously approved for sandbox use)\n\n*w_transport 2.3.2*\n- [x] [CP-1425 Fix inheritance of autoRetry settings for requests created by Client](https://github.com/Workiva/w_transport/pull/127)\n- [x] [CP-1384 Release w_transport 2.3.2](https://github.com/Workiva/w_transport/pull/128)\n\n- [x] Dependency Scan Clean\n\n## Additional Information\n\nReviewers: blainegarrett-wf, bradybecker-wf, michaelcarter-wf, mikekeil-wf\nWatchlist Notifications: None\n\n\t\tWhen this pull is merged I will use the following information:\n\t\tVersion: wf-home-html v2.2.4\n\t\tRelease Ticket(s): WORK-4189, WORK-4190\n\n***\n*Last updated on Friday, April 08 02:14 PM CST*"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/205470836",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-205470836",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 205470836,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T20:02:43Z",
    "updated_at": "2016-04-04T20:02:43Z",
    "body": "@michaelcarter-wf @mikekeil-wf @bradybecker-wf @hannahdeering-wf \r\n\r\nThanks for taking a look!"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/205490283",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-205490283",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 205490283,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T20:49:21Z",
    "updated_at": "2016-04-04T20:49:21Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/205499160",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-205499160",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 205499160,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-04T21:11:18Z",
    "updated_at": "2016-04-06T19:38:51Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/205991472",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-205991472",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 205991472,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-05T21:30:49Z",
    "updated_at": "2016-04-05T21:30:49Z",
    "body": "👍 "
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/206573756",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-206573756",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 206573756,
    "user": {
      "login": "codecov-wf",
      "id": 13698420,
      "avatar_url": "https://avatars.githubusercontent.com/u/13698420?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/codecov-wf",
      "html_url": "https://github.com/codecov-wf",
      "followers_url": "https://api.github.com/users/codecov-wf/followers",
      "following_url": "https://api.github.com/users/codecov-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/codecov-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/codecov-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/codecov-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/codecov-wf/orgs",
      "repos_url": "https://api.github.com/users/codecov-wf/repos",
      "events_url": "https://api.github.com/users/codecov-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/codecov-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-06T21:17:02Z",
    "updated_at": "2016-04-08T14:55:09Z",
    "body":
        "## [Current coverage][1] is `83.21%`\n> Merging **#395** into **master** will not affect coverage as of [`d53d1cb`][3]\n\n\n```diff\n@@            master    #395   diff @@\n======================================\n  Files           41      41       \n  Stmts          983     983       \n  Branches         0       0       \n  Methods          0       0       \n======================================\n  Hit            818     818       \n  Partial          0       0       \n  Missed         165     165       \n```\n\n> Review entire [Coverage Diff][4] as of [`d53d1cb`][3]\n\n\n[1]: https://codecov.workiva.net/github/Workiva/wf-home-html?ref=d53d1cbd52c3c4af35975d9058864dbc2d61c119\n[2]: https://codecov.workiva.net/github/Workiva/wf-home-html/features/suggestions?ref=d53d1cbd52c3c4af35975d9058864dbc2d61c119\n[3]: https://codecov.workiva.net/github/Workiva/wf-home-html/commit/d53d1cbd52c3c4af35975d9058864dbc2d61c119\n[4]: https://codecov.workiva.net/github/Workiva/wf-home-html/compare/b1b253bc4529334698510b04fe4a0db8312b843a...d53d1cbd52c3c4af35975d9058864dbc2d61c119\n\n> Powered by [Codecov](https://codecov.io). Updated on successful CI builds."
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/206588819",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-206588819",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 206588819,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-06T21:56:39Z",
    "updated_at": "2016-04-06T22:26:58Z",
    "body":
        "@mikekeil-wf @bradybecker-wf @michaelcarter-wf \r\n\r\nHad to make a tweak to prevent some jitter in classic Home.  I updated the preview gifs above.  New preview build: https://work-4131-1-dot-wf-home.appspot.com\r\n\r\nThanks!"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/206589800",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-206589800",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 206589800,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-06T22:00:53Z",
    "updated_at": "2016-04-06T22:00:53Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/206596463",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-206596463",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 206596463,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-06T22:28:31Z",
    "updated_at": "2016-04-06T22:28:31Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/206935535",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-206935535",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 206935535,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-07T14:40:14Z",
    "updated_at": "2016-04-07T14:40:14Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207467855",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207467855",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207467855,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T14:59:59Z",
    "updated_at": "2016-04-08T14:59:59Z",
    "body":
        "@michaelcarter-wf @mikekeil-wf @bradybecker-wf @blainegarrett-wf @theisensanders-wf \r\n\r\nHello!  I made a couple more tweaks, including adding padding around the Task grid container.\r\n\r\nUpdated preview deploy: https://work-4131-2-dot-wf-home.appspot.com/\r\n\r\nThanks!"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207472819",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207472819",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207472819,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T15:13:45Z",
    "updated_at": "2016-04-08T15:13:45Z",
    "body": ":+1: "
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207483377",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207483377",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207483377,
    "user": {
      "login": "michaelcarter-wf",
      "id": 4481523,
      "avatar_url": "https://avatars.githubusercontent.com/u/4481523?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcarter-wf",
      "html_url": "https://github.com/michaelcarter-wf",
      "followers_url": "https://api.github.com/users/michaelcarter-wf/followers",
      "following_url": "https://api.github.com/users/michaelcarter-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcarter-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcarter-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcarter-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcarter-wf/orgs",
      "repos_url": "https://api.github.com/users/michaelcarter-wf/repos",
      "events_url": "https://api.github.com/users/michaelcarter-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcarter-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T15:37:42Z",
    "updated_at": "2016-04-08T15:37:42Z",
    "body": "+1"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207483524",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207483524",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207483524,
    "user": {
      "login": "bradybecker-wf",
      "id": 6053448,
      "avatar_url": "https://avatars.githubusercontent.com/u/6053448?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bradybecker-wf",
      "html_url": "https://github.com/bradybecker-wf",
      "followers_url": "https://api.github.com/users/bradybecker-wf/followers",
      "following_url": "https://api.github.com/users/bradybecker-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/bradybecker-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bradybecker-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bradybecker-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/bradybecker-wf/orgs",
      "repos_url": "https://api.github.com/users/bradybecker-wf/repos",
      "events_url": "https://api.github.com/users/bradybecker-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bradybecker-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T15:38:14Z",
    "updated_at": "2016-04-09T02:47:58Z",
    "body": "👍 "
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207489717",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207489717",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207489717,
    "user": {
      "login": "jimhotchkin-wf",
      "id": 2872166,
      "avatar_url": "https://avatars.githubusercontent.com/u/2872166?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jimhotchkin-wf",
      "html_url": "https://github.com/jimhotchkin-wf",
      "followers_url": "https://api.github.com/users/jimhotchkin-wf/followers",
      "following_url": "https://api.github.com/users/jimhotchkin-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/jimhotchkin-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jimhotchkin-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jimhotchkin-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/jimhotchkin-wf/orgs",
      "repos_url": "https://api.github.com/users/jimhotchkin-wf/repos",
      "events_url": "https://api.github.com/users/jimhotchkin-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jimhotchkin-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T15:50:46Z",
    "updated_at": "2016-04-08T15:51:51Z",
    "body":
        "@blainegarrett-wf \r\n\r\n![preview](http://content.screencast.com/users/JimHotchkin/folders/Jing/media/5e868096-445a-411f-ad7b-9d9124f2eb1c/00000120.png)"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207495059",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207495059",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207495059,
    "user": {
      "login": "blainegarrett-wf",
      "id": 1480474,
      "avatar_url": "https://avatars.githubusercontent.com/u/1480474?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/blainegarrett-wf",
      "html_url": "https://github.com/blainegarrett-wf",
      "followers_url": "https://api.github.com/users/blainegarrett-wf/followers",
      "following_url": "https://api.github.com/users/blainegarrett-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/blainegarrett-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/blainegarrett-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/blainegarrett-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/blainegarrett-wf/orgs",
      "repos_url": "https://api.github.com/users/blainegarrett-wf/repos",
      "events_url": "https://api.github.com/users/blainegarrett-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/blainegarrett-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T16:05:52Z",
    "updated_at": "2016-04-08T16:05:52Z",
    "body": "+1 QA'd the padding change via screenshot"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207554254",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207554254",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207554254,
    "user": {
      "login": "mikekeil-wf",
      "id": 1456034,
      "avatar_url": "https://avatars.githubusercontent.com/u/1456034?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikekeil-wf",
      "html_url": "https://github.com/mikekeil-wf",
      "followers_url": "https://api.github.com/users/mikekeil-wf/followers",
      "following_url": "https://api.github.com/users/mikekeil-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikekeil-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikekeil-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikekeil-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/mikekeil-wf/orgs",
      "repos_url": "https://api.github.com/users/mikekeil-wf/repos",
      "events_url": "https://api.github.com/users/mikekeil-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikekeil-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T18:50:52Z",
    "updated_at": "2016-04-08T18:50:52Z",
    "body":
        "***DEV QA +10***\r\n- [x] Classic Home in Safari/Chrome/Firefox/IE\r\n- [x] Shell Home Chrome/Firefox/IE\r\n\r\nOne slight visual nuance we noticed while in the home shell was the action buttons being hidden prematurely with the left nav collapsed.  @hannahdeering-wf would you mind taking a peak?\r\n\r\n![4131](https://cloud.githubusercontent.com/assets/1456034/14394218/c2000202-fd90-11e5-914e-3ef2f2bdf96c.gif)\r\n"
  },
  {
    "url": "https://api.github.com/repos/Workiva/wf-home-html/issues/comments/207564535",
    "html_url": "https://github.com/Workiva/wf-home-html/pull/395#issuecomment-207564535",
    "issue_url": "https://api.github.com/repos/Workiva/wf-home-html/issues/395",
    "id": 207564535,
    "user": {
      "login": "hannahdeering-wf",
      "id": 5629760,
      "avatar_url": "https://avatars.githubusercontent.com/u/5629760?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/hannahdeering-wf",
      "html_url": "https://github.com/hannahdeering-wf",
      "followers_url": "https://api.github.com/users/hannahdeering-wf/followers",
      "following_url": "https://api.github.com/users/hannahdeering-wf/following{/other_user}",
      "gists_url": "https://api.github.com/users/hannahdeering-wf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/hannahdeering-wf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/hannahdeering-wf/subscriptions",
      "organizations_url": "https://api.github.com/users/hannahdeering-wf/orgs",
      "repos_url": "https://api.github.com/users/hannahdeering-wf/repos",
      "events_url": "https://api.github.com/users/hannahdeering-wf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/hannahdeering-wf/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-08T19:14:03Z",
    "updated_at": "2016-04-08T19:14:03Z",
    "body":
        "Hmmm... I think we're using a consistent breakpoint to hide those (tablet width). \r\nI see 2 options:\r\n1) make the hiding smaller so it actually knows about the width of the title\r\n2) make a new ticket for collapsing the action buttons into one icon with a dropdown when we encounter this so we don't have to hide them completely."
  }
];
